apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fleet-server-ingress
  namespace: elastic
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fleet-server.kickb.dev
      secretName: wagtail-tls-secret3
  rules:
    - host: fleet-server.kickb.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fleet-server
                port:
                  number: 8220
