apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wagtail-ingress
  namespace: website
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kickb.dev
      secretName: wagtail-tls-secret2
  rules:
    - host: kickb.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-wagtail-service
                port:
                  number: 80
              # service:
              #   name: wagtail-service
              #   port:
              #     number: 8000