apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sysreptor-ingress
  namespace: sysreptor
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - reporting.kickb.dev
      secretName: wagtail-tls-secret2
  rules:
    - host: reporting.kickb.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sysreptor
                port:
                  number: 80
