apiVersion: v1
kind: Secret
metadata:
  name: wagtail-postgres-credentials
  namespace: website
type: Opaque
data:
  POSTGRES_USER: d2FndGFpbA==
  POSTGRES_DB: d2FndGFpbA==
  POSTGRES_PASSWORD: d2FndGFpbA==
  SECRET_KEY: d2FndGFpbA==
