apiVersion: v1
kind: Service
metadata:
  name: fleet-server
  namespace: default
spec:
  selector:
    app: fleet-server
  ports:
    - protocol: TCP
      port: 8220
      targetPort: 8220
  type: ClusterIP